# Generated by Django 5.0.6 on 2024-05-28 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="pub_data",
            new_name="pub_date",
        ),
    ]
